resources:
- dep-globex-ui-unsigned.yaml

patches:
- target:
    kind: Deployment
    name: globex-ui-unsigned
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/image
      value:  "quay.apps.cluster-9ktkv.9ktkv.sandbox2699.opentlc.com/quayadmin/globex-ui-unsigned:main-93cc339f426c05862bdb2b69d4fbb4fa353626dd"