apiVersion: v1
kind: ResourceQuota
metadata:
  name: quota-develop
  namespace: aws-dev-cluster
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 1Gi
    limits.cpu: "4"
    limits.memory: 4Gi
    pods: "50"
