resources:
- ../../base

patches:
- target:
    kind: Service
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/image
      value:  "quay.apps.cluster-kfdwd.kfdwd.sandbox1247.opentlc.com/quayadmin/devsecops:main-5345343dfwedw232"
