apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: eventingsc
spec:
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
        autoscaling.knative.dev/target: "1"
    spec:
      containers:
      - image: quay.apps.cluster-jwx8g.jwx8g.sandbox3014.opentlc.com/quayadmin/devsecops:main-mandyye7yr7he7dhe8
