apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: eventingsv
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/target: "1"
    spec:
      containers:
      - image: quay.apps.cluster-kfdwd.kfdwd.sandbox1247.opentlc.com/quayadmin/devsecops:main-7h36db3y6bdyeb
