resources:
- ../../base

patches:
- path: traffic-routing.yaml
  target:
    kind: Service
- target:
    kind: Service
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/image
      value:         "quay.apps.cluster-jwx8g.jwx8g.sandbox3014.opentlc.com/quayadmin/devsecops:main-mandyye7yr7he7dhe8"
