resources:
- ../../base

patches:
- path: traffic-routing.yaml
  target:
    kind: Service
- target:
    kind: Service
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/image
      value:                "quay.apps.cluster-z5p6q.z5p6q.sandbox262.opentlc.com/quayadmin/devsecops:master-47fdfa84f625ebc14e4ff4f8a86327cd37946348"
